rapport1.zip: faits/faits.pdf schema-orm.pdf schema-relationnel.pdf bartender.sqlite requetes.sql conception/conception.pdf
	cp faits/faits.pdf faits.pdf
	cp conception/conception.pdf conception.pdf
	zip rapport1.zip faits.pdf schema-orm.pdf schema-relationnel.pdf bartender.sqlite requetes.sql conception.pdf
	rm faits.pdf conception.pdf
