rapport1.zip: README.md faits/faits.pdf schema-orm.pdf schema-relationnel.pdf bartender.sqlite requetes.sql conception/conception.pdf population/population.pdf
	cp faits/faits.pdf faits.pdf
	cp conception/conception.pdf conception.pdf
	cp population/population.pdf population.pdf
	zip rapport1.zip README.md faits.pdf schema-orm.pdf schema-relationnel.pdf bartender.sqlite requetes.sql conception.pdf population.pdf
	rm faits.pdf conception.pdf population.pdf
